services:
  - type: web
    name: certificate-validator
    env: python
    buildCommand: "pip install -r requirements.txt && apt-get update && apt-get install -y tesseract-ocr"
    startCommand: "cd admin && gunicorn --bind 0.0.0.0:$PORT app:app"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: TESSERACT_CMD
        value: /usr/bin/tesseract
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000